#!/bin/bash

output "ssh_command" {
  value = "ssh -i my-ec2-keypair.pem centos@${aws_instance.app_server.public_ip}"
}

output "ec2_ip" {
    value = aws_instance.app_server.public_ip
  
}


output "vpc_id" {
  value = module.vpc.vpc_id
}
