#!/bin/bash

provider "aws" {
    region = "us-east-1"
  
}

#create vpc

module "vpc" {
  source = "terraform-aws-modules/vpc/aws"

  name = "utc-app1"
  cidr = "192.168.0.0/16"

  azs             = ["us-east-1a", "us-east-1b",]
  private_subnets = ["192.168.1.0/24", "192.168.2.0/24"]
  public_subnets  = ["192.168.101.0/24", "192.168.102.0/24"]

  #  enable_nat_gateway = false
  # enable_vpn_gateway = false

enable_nat_gateway = true
enable_vpn_gateway = true
enable_dns_hostnames = true

  tags = {
    Name = "utc-app1"
    env = "Dev"
    team = "wdp"
    created-by = "asn"



}
}
